/*******************************************************************************
** Copyright 2024-present HMS Industrial Networks AB.
** Licensed under the MIT License.
********************************************************************************
** File Description:
** ABCC driver error codes
********************************************************************************
*/
#ifndef ABCC_ERROR_CODES_H_
#define ABCC_ERROR_CODES_H_

typedef enum ABCC_ErrorCodeType
{
   ABCC_EC_NO_ERROR = 0,
   ABCC_EC_INTERNAL_ERROR = 1,
   ABCC_EC_LINK_CMD_QUEUE_FULL = 2,
   ABCC_EC_LINK_RESP_QUEUE_FULL = 3,
   ABCC_EC_OUT_OF_MSG_BUFFERS = 4,
   ABCC_EC_TRYING_TO_FREE_NULL_POINTER = 5,
   ABCC_EC_INCORRECT_OPERATING_MODE = 6,
   ABCC_EC_INCORRECT_STATE = 7,
   ABCC_EC_RESP_MSG_E_BIT_SET = 8,
   ABCC_EC_WRPD_SIZE_ERR = 9,
   ABCC_EC_RDPD_SIZE_ERR = 10,
   ABCC_EC_RDMSG_SIZE_ERR = 11,
   ABCC_EC_INVALID_RESP_SOURCE_ID = 12,
   ABCC_EC_MODULE_NOT_DECTECTED = 13,
   ABCC_EC_PARAMETER_NOT_VALID = 14,
   ABCC_EC_MODULE_ID_NOT_SUPPORTED = 15,
   ABCC_EC_DEFAULT_MAP_ERR = 16,
   ABCC_EC_ERROR_IN_READ_MAP_CONFIG = 17,
   ABCC_EC_ERROR_IN_WRITE_MAP_CONFIG = 18,
   ABCC_EC_INTSTATUS_NOT_SUPPORTED_BY_DRV_IMPL = 19,
   ABCC_EC_MODCAP_NOT_SUPPORTED_BY_DRV_IMPL = 20,
   ABCC_EC_LEDSTATUS_NOT_SUPPORTED_BY_DRV_IMPL = 21,
   ABCC_EC_SPI_OP_NOT_ALLOWED_DURING_SPI_TRANSACTION = 22,
   ABCC_EC_WRMSG_SIZE_ERR = 23,
   ABCC_EC_MSG_BUFFER_CORRUPTED = 24,
   ABCC_EC_MSG_BUFFER_ALREADY_FREED = 25,
   ABCC_EC_NO_RESOURCES = 26,
   ABCC_EC_HW_INIT_FAILED = 27,
   ABCC_EC_RCV_CMD_SIZE_EXCEEDS_BUFFER = 28,
   ABCC_EC_RCV_RESP_SIZE_EXCEEDS_BUFFER = 29,
   ABCC_EC_UNEXPECTED_NULL_PTR = 30,
   ABCC_EC_OUT_OF_CMD_SEQ_RESOURCES = 31,
   ABCC_EC_HAL_ERR = 32,
   ABCC_EC_ERROR_IN_PD_MAP_CONFIG = 33,
   ABCC_EC_ERROR_RESP_SEGMENTATION = 34,
   ABCC_EC_BAD_ASSEMBLY_INSTANCE = 35,
   ABCC_EC_UNSUPPORTED_DATA_TYPE = 36,
   ABCC_EC_CHECKSUM_MISMATCH = 37,
   ABCC_EC_SETUP_FAILED = 38,
   ABCC_EC_MSG_BUFFER_OVERRUN = 39,
   ABCC_EC_MODULE_NOT_ANSWERING = 40,
   ABCC_EC_CMD_SEQ_RETRY_LIMIT = 41,
   ABCC_EC_UNKNOWN_ENDIAN = 42,
   ABCC_EC_ASSERT_FAILED = 43,
   ABCC_EC_PD_SIZE_MISMATCH = 44,
   ABCC_EC_SET_ENUM_ANSI_SIZE       = 0x7FFF
}
ABCC_ErrorCodeType;

#endif
